[theme]
primaryColor = "#F7B267"
backgroundColor = "#1a1917"
secondaryBackgroundColor = "#201f1d"
textColor = "#FFFCF2"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
